#!/usr/bin/env python
import sys
import time
import papermill as pm

retry_limit = 3
retry = 0

while retry < retry_limit:
    try:
        pm.execute_notebook(sys.argv[1], sys.argv[2])
        break
    except RuntimeError as e:
        retry += 1
        if str(e).strip() == 'Kernel died before replying to kernel_info' and retry < retry_limit:
            sys.stderr.write('Retrying after 5 seconds...\n')
            time.sleep(5)
        else:
            raise e
